eval %sh{
    if ! [ -d $HOME/.config/kak ]; then
      mkdir -p $HOME/.config/kak
    fi
}

eval %sh{
    if ! [ -d $HOME/.config/kak/plugins/plug.kak ]; then
      mkdir -p $HOME/.config/kak/plugins/plug.kak
      git clone https://github.com/andreyorst/plug.kak.git ~/.config/kak/plugins/plug.kak
    fi
}

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "ul/kak-lsp" do %{
    cargo install --force --path .
} config %{
    set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"
    set-option global lsp_diagnostic_line_error_sign "✗"
    set-option global lsp_diagnostic_line_warning_sign "⚠"
    hook global WinSetOption filetype=(c|cpp|rust|sh|lua|elm) %{
        map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
        lsp-enable-window
        lsp-auto-hover-disable
        lsp-auto-hover-insert-mode-disable
        lsp-auto-signature-help-enable
        set-option window lsp_hover_anchor false
        set-face window DiagnosticError default+u
        set-face window DiagnosticWarning default+u
    }

    hook global KakEnd .* lsp-exit
}


map global normal '<c-f>' ': fzf-mode<ret>' -docstring 'fzf mode'
plug "andreyorst/fzf.kak" defer fzf %{
    set-option global fzf_preview_width '65%'
    set-option global fzf_file_command "fd --hidden --exclude '/.git/' --type f --follow"
    set-option global fzf_highlight_command "bat"
    set-option global fzf_grep_command "rg --hidden --glob '!/.git/' --line-number --no-column --no-heading --color=never ''"
    set-option global fzf_window_map "ctrl-t"
    set-option global fzf_use_main_selection false
}

plug "delapouite/kakoune-text-objects"

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global tabstop 4
    set-option global indentwidth 4
    set-option global softtabstop 4
    expandtab
} config %{
    hook global WinSetOption filetype=(css|sh) %{
        set-option window tabstop 2
        set-option window indentwidth 2
        set-option window softtabstop 2
    }
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
}

plug "alexherbo2/auto-pairs.kak" commit "3e529e8002fe07e952c3a895f50dc749eb2b40de" config %{
    hook global WinSetOption filetype=rust %{
        set-option buffer auto_pairs ( ) { } [ ] '"' '"' ` ` “ ” ‘ ’ « » ‹ ›
    }
}

plug "alexherbo2/surround.kak" commit "f13b0ad8dfc9cca07fce25ca753139882a3acb69" %{
    map global user 's' ': surround<ret>'         -docstring "surround selection"
    map global user 'S' ': surround _ _ * *<ret>' -docstring 'Enter surround mode with extra surrounding pairs'
    set-option global surround_begin auto-pairs-disable
    set-option global surround_end auto-pairs-enable
}

plug 'Anfid/cosy-gruvbox.kak' theme config %{
    colorscheme cosy-gruvbox
}

plug "andreyorst/powerline.kak" defer powerline %{
    set-option global powerline_format 'git filetype bufname line_column position'
    powerline-theme base16-gruvbox
} config %{
    powerline-start
}

plug "https://gitlab.com/Screwtapello/kakoune-cargo" config %{
    hook global WinSetOption filetype=rust %{
        map window user "c" ": enter-user-mode cargo<ret>" -docstring "cargo mode"
    }
}

plug "chambln/kakoune-readline" config %{
    hook global WinCreate .* %{
        readline-enable
        unmap window normal <c-e> i
    }
}

plug "TeddyDD/kakoune-wiki" config %{
    wiki-setup %sh{ echo "$HOME/documents/wiki" }
}

plug 'delapouite/kakoune-livedown'

set global ui_options ncurses_assistant=none
hook global WinCreate .* %{
    add-highlighter window/ number-lines -hlcursor
    add-highlighter window/ show-whitespaces -lf ' '
    add-highlighter window/ show-matching
    git show-diff
}

# Rust autoformatting
hook global WinSetOption filetype=rust %{
    set buffer formatcmd "rustfmt --edition=2018"

    hook -group rustfmt buffer BufWritePre .* %{
        format-buffer
    }
}

hook global WinSetOption filetype=elm %{
    set buffer matching_pairs ( ) { } [ ]
    set buffer formatcmd "elm-format --stdin"

    hook -group elmfmt buffer BufWritePre .* %{
        format-buffer
    }
}

define-command -params 0..1 -file-completion split %{
    evaluate-commands %sh{
        file="$1"
        if [ -z "$file" ]; then
          printf 'x11-terminal kak -c "%s"\n' "$kak_session"
        else
          printf 'x11-terminal kak -c "%s" -e edit "%s"\n' "$kak_session" "$file"
        fi
    }
}

# Modes
map global normal "'" ':'
map global normal <a-t> <a-i>
map global normal b v
map global normal B V
map global normal <a-r> <a-i>

# Movement
map global normal n h
map global normal e j
map global normal i k
map global normal o l
map global normal N H
map global normal E J
map global normal I K
map global normal O L

map global normal l b
map global normal u w
map global normal y e
map global normal L B
map global normal U W
map global normal Y E
map global normal <a-l> <a-b>
map global normal <a-u> <a-w>
map global normal <a-y> <a-e>
map global normal <a-L> <a-B>
map global normal <a-U> <a-W>
map global normal <a-Y> <a-E>

map global normal k n
map global normal K N
map global normal <a-k> <a-n>
map global normal <a-K> <a-N>

map global normal <a-n> gi
map global normal <a-o> gl
map global normal <a-N> Gi
map global normal <a-O> Gl
map global normal <a-e> Vjjjjj<esc>
map global normal <a-i> Vkkkkk<esc>

map global normal <c-e> ': lsp-definition<ret>' -docstring "jump to definition (LSP)"

# Editing
map global normal a i
map global normal A I

map global normal t a
map global normal T A

map global normal h o
map global normal H O
map global normal <a-h> <a-o>
map global normal <a-H> <a-O>

map global normal z u
map global normal Z U
map global normal <a-z> <a-u>
map global normal <a-Z> <a-U>

map global normal c y
map global normal <a-c> ': copy-primary-to-clipboard<ret>'

map global normal v p
map global normal V P
map global normal <a-v> <a-p>
map global normal <a-V> <a-P>

map global normal w c
map global normal <a-w> <a-c>

map global normal p z
map global normal P Z
map global normal <a-p> <a-z>
map global normal <a-P> <a-Z>

define-command copy-primary-to-clipboard %{
    execute-keys -draft '<space><a-|> xclip -selection clipboard<ret>'
    echo -markup "{Information}Copied %val[selection_length] characters to clipboard"
} -docstring 'Copy primary selection to clipboard'

# Navigation
map global normal -- - ': x11-terminal ranger<ret>'

hook global InsertChar \t %{ try %{
  execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}

hook global InsertDelete ' ' %{ try %{
  execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}

# Tab completion
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# View
map global goto n h       -docstring "line begin"
map global goto o l       -docstring "line end"
map global view e 'jjjjj' -docstring "scroll down 5 lines"
map global view i 'kkkkk' -docstring "scroll up 5 lines"

# Clients
declare-user-mode client
map global normal <c-w> ': enter-user-mode client<ret>' -docstring 'client mode'
map global client s ': split<ret>'

# Git
declare-user-mode git
map global user v ': enter-user-mode git<ret>' -docstring 'git mode'

map global git s  ': git status<ret>'          -docstring 'status'
map global git d  ': git diff<ret>'            -docstring 'diff'
map global git l  ': git log<ret>'             -docstring 'log'
map global git n  ': git next-hunk<ret>vc'     -docstring 'jump to next hunk'
map global git p  ': git prev-hunk<ret>vc'     -docstring 'jump to previous hunk'

define-command -hidden git-status-jump %{
    try %{
        execute-keys '<a-x>s^\t(?:(?:both )?modified:|added:|new file:|copied:|deleted(?: by \w+)?:|renamed:\s+.*\s->)?\s+([^\n]+)<ret>'
        evaluate-commands -try-client %opt{jumpclient} -verbatim -- edit -existing %reg{1}
        try %{ focus %opt{jumpclient} }
    }
}

hook global WinSetOption filetype=git-status %{
    map buffer normal <ret> ': git-status-jump<ret>'   -docstring 'Jump to file'
    map buffer normal <c-n> '/<c-v><c-i><ret>gi'       -docstring 'Next changed file'
    map buffer normal <c-p> 'gh<a-/><c-v><c-i><ret>gi' -docstring 'Previous changed file'
}

define-command -hidden git-log-jump %{
    try %{
        execute-keys -save-regs 'c/' 'j<a-/>^commit<ret> <a-x> s^commit\s+\K[0-9a-f]+<ret> "cy :<space>git<space>show<space><c-r>c<ret>'
    }
}

hook global WinSetOption filetype=git-log %{
    map buffer normal <ret> ': git-log-jump<ret>' -docstring 'Jump to commit'
    map buffer normal <c-n> '/^commit<ret>gi'     -docstring 'Next commit'
    map buffer normal <c-p> '<a-/>^commit<ret>gi' -docstring 'Previous commit'
}

define-command -hidden diff-next-change %{
    execute-keys -save-regs / '/@@\s+-\d+,\d+\s\+\d+.\d+\s+@@<ret>jgh'
}
define-command -hidden diff-prev-change %{
    execute-keys -save-regs / 'kgh<a-/>@@\s+-\d+,\d+\s\+\d+.\d+\s+@@<ret>jgh'
}
define-command -hidden diff-jump-to-line %{
    try %{ execute-keys -draft ';<a-?>^diff<ret>: nop %sh{ printf "%s" "$kak_selection" > /tmp/kak-git-show-${kak_session} }<ret>' }
    evaluate-commands %sh{
        parse_diff_segment() {
            perl -e '
                foreach $line (<>) {
                    if ($line =~ /^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)?/) {
                        $last = "-";
                        $src_lines = $1 - 1;
                        $dst_lines = $2 - 1;
                    } elsif ($line =~ /^--- a\/(.+)/) {
                        $src_file = $1;
                    } elsif ($line =~ /^\+\+\+ b\/(.+)/) {
                        $dst_file = $1;
                    } elsif ($line =~ /^\s/) {
                        $last = " ";
                        $src_lines += 1;
                        $dst_lines += 1;
                    } elsif ($line =~ /^\+/) {
                        $last = "+";
                        $dst_lines += 1;
                    } elsif ($line =~ /^-/) {
                        $last = "-";
                        $src_lines += 1;
                    } elsif ($line =~ /^index (\w+)\.\.(\w+)/) {
                        $src_idx = $1;
                        $dst_idx = $2;
                    }
                    $char = length($line) - 1;
                }
                if ($char < 1) { $char = 1 }

                if ($last eq "+") {
                    print "$dst_idx $dst_file $dst_lines $char\n"
                } else {
                    print "$src_idx $dst_file $src_lines $char\n"
                }
            ' $1
        }
        read hash file line col <<< $(parse_diff_segment /tmp/kak-git-show-${kak_session})
        rm /tmp/kak-git-show-$kak_session

        top_line=${kak_window_range%% *}
        offset=$(($kak_cursor_line - $top_line - 1))

        case $(git hash-object $file) in
            "$hash"*)
                echo "edit! $file
                      evaluate-commands -client ${kak_client} select ${line}.${col},${line}.${col}
                      execute-keys -client ${kak_client} vt${offset}vk"
                ;;
            *)
                output="$(mktemp -d -t kak-git-show-XXXXXXXX)/fifo"
                mkfifo ${output}
                ( git show $hash > ${output} 2>&1 && rm -r $(dirname ${output}) ) > /dev/null 2>&1 < /dev/null &
                echo "edit! -fifo ${output} $hash:$file
                      hook buffer BufCloseFifo .* %{
                          evaluate-commands -client ${kak_client} select ${line}.${col},${line}.${col}
                          execute-keys -client ${kak_client} vt${offset}vk
                      }"
                ;;
        esac
    }
}

hook global WinSetOption filetype=diff %{
    map buffer normal <c-n> ": diff-next-change<ret>"  -docstring 'Next change'
    map buffer normal <c-p> ": diff-prev-change<ret>"  -docstring 'Previous change'
    map buffer normal <ret> ": diff-jump-to-line<ret>" -docstring 'Jump to changed line'
}

hook global BufWritePost .* %{
    git update-diff
}
